### ISSUE TITLE
streaming server not avaible

### ISSUE THREAD

**Issue by manmohangurram** [sleeyax/stremio-streaming-server#15]
I am using this command to start the server
`docker run -e FORCE_HTTPS=1 -e FIX_CORS=1 ....`

and its started
![Screenshot_3](https://user-images.githubusercontent.com/42374539/183145546-eab2cb9e-217c-4d3f-96a3-b898aa60338f.png)

but in the hosted site its showing Streaming server is not available.

**Comment by sleeyax** [comment]
Please provide more information.

- Which hosted site?
- Are you using a reverse proxy (because I see you enabled https patch)?
- Are you sure you changed streaming server ip and port correctly? Can you ping it?

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry for bothering but im also having the same issue, I port forwarded my router and applied the FORCE_HTTPS patch but whenever i try to connect using public ip or local ip, I still get the error that streaming server is not available. 

Whenever i tried http instead of https, It would say its available. Im not sure if this is a bug but im not sure what to do at this point.

**Comment by Goldenfreddy0703** [comment]
Actually nevermind, i figured it out. I just had to play a show in order for my settings and configuration to save. 
Thank you

**Comment by sleeyax** [comment]
Great, I'm marking this as solved then.
