### ISSUE TITLE
It works but i get the message "could not update casting device" in all browsers

### ISSUE THREAD

**Issue by mtoensing** [sleeyax/stremio-streaming-server#17]
I can go to [mylocalip]:11470 and it redirect to https://app.strem.io/shell-v4.4/?streamingServer=[mylocalip]:11470 And it works. I can install the relevant plugins and I can watch them on my TV and macOS Browser. But I get this message sometimes: 

could not update casting device 

in the top-right corner: 

<img width="325" alt="Screen Shot 2022-10-19 at 22 20 09" src="https://user-images.githubusercontent.com/136737/196795698-dc9a111c-ec23-47e0-93e2-8ec68276a71f.png">

Do you have any idea how to prevent this? Everything works, but I would rather not remove the message,

**Comment by sleeyax** [comment]
If everything works it's probably a bug in stremio-web or the streaming server itself.

**Comment by M1-K3** [comment]
Did you tried to force https? https://github.com/sleeyax/stremio-streaming-server/issues/10#issuecomment-1174508779

**Comment by vliapis** [comment]
Same thing. HTTPS endpoint aint working. I get these errors:
`Cannot update settings ENOENT: no such file or directory, open '/root/.stremio-server/server-settings.json'
(node:9) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
`
And although it shows that port 12470 is opened, it's actualy not:

EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470

but when running netstat, 12470 appears closed.

**Comment by lenuswalker** [comment]
Also having this issue. Stream server might be offline.

**Comment by hvmzx** [comment]
I am getting the same issue unfortunately :/

**Comment by sleeyax** [comment]
Hi, the Stremio team has recently announced an **official** docker image: https://github.com/Stremio/server-docker This project will therefore no longer be maintained.
