### ISSUE TITLE
add instructions on how to deploy on heroku

### ISSUE THREAD

**Issue by r-bromfield** [sleeyax/stremio-streaming-server#4]
this would be helpful information

**Comment by sleeyax** [comment]
Find out how to run docker containers on heroku.

Maybe this article will help:

https://devcenter.heroku.com/articles/container-registry-and-runtime

**Comment by sleeyax** [comment]
I don't want to add specific instructions for deployment platforms like Heroku to this project README because you can just put in a little effort and look into documentation of said platform for that. If it can run docker containers it should work. Most users will want to run the streaming server locally on LAN anyways.
