### ISSUE TITLE
stremio and raspberry pi4

### ISSUE THREAD

**Issue by vliapis** [sleeyax/stremio-streaming-server#9]
Hello, the stremio version docker is pulling is for x86/64 platform or agnostic (meaning it can work with raspberry's arm64).
i get this error:

docker run -p 11470:11470 -v ${PWD}:/root/.stremio-server --name=stremio-streaming-server sleeyax/stremio-streaming-server
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/593fde7a3bbe0639dc1bdbc84acaed96f7050c08a7d860e02098f492aa4ef3b1-init: mount target=/var/lib/docker/aufs/mnt/593fde7a3bbe0639dc1bdbc84acaed96f7050c08a7d860e02098f492aa4ef3b1-init data=br:/var/lib/docker/aufs/diff/593fde7a3bbe0639dc1bdbc84acaed96f7050c08a7d860e02098f492aa4ef3b1-init=rw:/var/lib/docker/aufs/diff/3abb678ec804f3cbfde9551f839522cdc817f8bf9fb87d9ee6b8e3c31e24b5b7=ro+wh:/var/lib/docker/aufs/diff/1803f7a5303f2d5fdaeab55564912b6d31905a623554e6a92bc791cb71206cae=ro+wh:/var/lib/docker/aufs/diff/609c192a437a27bd143ee9e87f6ec13926fe91c0c94224058b0d32d293e8826a=ro+wh:/var/lib/docker/aufs/diff/75c7dd76e1f07979485b4b472b0af878b59f3b647d537c32b5f5383097235568=ro+wh:/var/lib/docker/aufs/diff/9f6f8570f3e87651faf4c08e1018ed981b353fd85bfc0ca9c36c28ba9254a17e=ro+wh:/var/lib/docker/aufs/diff/7962a1936af15e248dba3d725bcb099429f6d64757fd7767fbc7878ca36d13f0=ro+wh:/var/lib/docker/aufs/diff/5491519218b5a5b7f0227d013356aed6f64ea33e172d5785fcd5b2dc0184dbfe=ro+wh:/var/lib/docker/aufs/diff/dce1df84fe8f1d42eae274e81540f1690a3e912b5736c9ce03b38a3d4303dc35=ro+wh:/var/lib/docker/aufs/diff/641d8e583879ecb845cf7b78fee610e330e6f2c928e0c381e0cfb3e915b2c4eb=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument.

**Comment by sleeyax** [comment]
~~I'm not sure I understand your first sentence. You mean to say you are using a raspberry pi? Which model?~~ sorry didn't check title.

Also, try to run docker with sudo.

**Comment by sleeyax** [comment]
Just flashed a new image to my rpi 4 and tried it out. Everything works fine on my end. Follow this guide to make sure docker is installed properly: https://phoenixnap.com/kb/docker-on-raspberry-pi

Then, make sure to run the full command as described in this project's README. You can use `/var/tmp/stremio-streaming-server` as the host's volume mount if you're not sure where to mount it.

I can't help you any further because I'm unable to reproduce this issue. Reopen if you are still experiencing this issue and when you can provide more information.
